### PR TITLE
[Outlook] (Smart Alerts) Fixes accessibility and support issues

### PR DESCRIPTION
**Pull request by samantharamon**
|        Q        |                    A                    |
| --------------- | --------------------------------------- |
| Bug fix?        | yes |
| New feature?    | no |
| New sample?     | no |
| Related issues? | N/A |

## What's in this Pull Request?

- Updates the button in the add-in task pane for keyboard accessibility. Fixes color contrast issues.
- Updates the task pane screenshot.
- ~~Adds a note on supported clients.~~ (addressed in #442)
- Minor code refactoring.

## Guidance

See above.

### CODE REVIEW

**Review by davidchesnut — CHANGES_REQUESTED** [review]
The overview images needs the following color contrasts fixed:
- Section 2, green background under "Add-ins Sample: marketing" does not pass.
- Section 2, blue-green background under "Office Add-ins 
Sample: sales" does not pass.
Section 1: Grey background with white text does not pass (text is not completely white.)
Section 4: Blue background with white text does not pass (text is not completely white.)

**Comment by samantharamon** [comment]
> The overview images needs the following color contrasts fixed:
> 
> * Section 2, green background under "Add-ins Sample: marketing" does not pass.
> * Section 2, blue-green background under "Office Add-ins
>   Sample: sales" does not pass.
>   Section 1: Grey background with white text does not pass (text is not completely white.)
>   Section 4: Blue background with white text does not pass (text is not completely white.)

Thanks for the feedback, @davidchesnut. I've been working on addressing these, but ran into an issue with the category list/expanded dropdown field in the task pane. It appears that I'm unable to override the background color when a category is selected. I'm going to test using another form type (maybe checkboxes?) or see about creating a custom field for it. Regarding your Section 4 feedback, I confirmed that the buttons colors pass the contrast tests (foreground: #FFFFFF, background: #005D95). Let me know if I need to make further adjustments.

**Review by davidchesnut — APPROVED** [review]
Ran and it works. But please change the :::image tags back. They don't work in GitHub markdown.

**Comment by samantharamon** [comment]
The changes to the category list/expanded dropdown field requires extensive changes. I'll address this in a separate PR. Internal work item: 7333950

**Pull request merged**
