### PR TITLE
Adding changes to make possible to debug blazor add-in

### PR DESCRIPTION
**Pull request by thaystg**
Adressing this question:
https://github.com/OfficeDev/Office-Add-in-samples/issues/444

Depends on a PR on CBA, I will add the link for the PR here soon.
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_git/CBA/pullrequest/442150

https://user-images.githubusercontent.com/4503299/208124863-8f5a4a70-e8cd-4ad8-b2c9-2c5ed2e71ba0.mp4

### CODE REVIEW

**Comment by mb-jp** [comment]
I cloned your fork but can't get this to work, I have tested with Microsoft Visual 17.5.0 Preview 2.0 and Microsoft Visual Studio 17.4.4.
with "just my code" disabled.
Are there any other requirements to make it work?

**Comment by thaystg** [comment]
Yes, my PR on VS side is not reviewed/approved/merged yet.

**Comment by aafvstam** [comment]
Video looks good, very happy ... is there a version/ETA for me to know when I can test this?
@davidchesnut maybe you can test before that as you are also 'internal' 😜?

**Comment by thaystg** [comment]
@davidchesnut can you approve and merge this change please?
Thanks!

**Review by davidchesnut — APPROVED** [review]
Looks great! Thanks for the help on this!

**Pull request merged**
